"""empty message

Revision ID: 1544e1eed796
Revises: 1d77aca86c9a
Create Date: 2016-01-10 22:25:15.264779

"""

# revision identifiers, used by Alembic.
revision = '1544e1eed796'
down_revision = '1d77aca86c9a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Unicode(length=100), nullable=False),
    sa.Column('name', sa.Unicode(length=200), nullable=True),
    sa.Column('password', sa.Unicode(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=40), nullable=True),
    sa.Column('description', sa.Unicode(length=400), nullable=True),
    sa.Column('user_id', sa.Unicode(length=200), nullable=True),
    sa.Column('client_id', sa.Unicode(length=40), nullable=True),
    sa.Column('client_secret', sa.Unicode(length=55), nullable=False),
    sa.Column('is_confidential', sa.Boolean(), nullable=True),
    sa.Column('redirect_uris_text', sa.UnicodeText(), nullable=True),
    sa.Column('default_scopes_text', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_index(op.f('ix_clients_client_secret'), 'clients', ['client_secret'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Unicode(length=40), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_type', sa.Unicode(length=40), nullable=True),
    sa.Column('access_token', sa.Unicode(length=255), nullable=True),
    sa.Column('refresh_token', sa.Unicode(length=255), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('_scopes', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_table('grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Unicode(length=40), nullable=False),
    sa.Column('code', sa.Unicode(length=255), nullable=False),
    sa.Column('redirect_uri', sa.Unicode(length=255), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('_scopes', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grants_code'), 'grants', ['code'], unique=False)
    op.drop_table('grant')
    op.drop_table('token')
    op.drop_table('user')
    op.drop_table('client')
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'user_id')
    op.create_table('client',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u"nextval('client_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('client_secret', sa.VARCHAR(length=55), autoincrement=False, nullable=False),
    sa.Column('is_confidential', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('redirect_uris_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('default_scopes_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'client_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u"nextval('user_id_seq'::regclass)"), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'user_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('token',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_type', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_scopes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], [u'client.client_id'], name=u'token_client_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'token_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'token_pkey')
    )
    op.create_table('grant',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('redirect_uri', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_scopes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], [u'client.client_id'], name=u'grant_client_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'grant_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'grant_pkey')
    )
    op.drop_index(op.f('ix_grants_code'), table_name='grants')
    op.drop_table('grants')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_clients_client_secret'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('users')
    ### end Alembic commands ###
