"""empty message

Revision ID: 3f64830dd323
Revises: 1544e1eed796
Create Date: 2016-01-27 22:33:29.978942

"""

# revision identifiers, used by Alembic.
revision = '3f64830dd323'
down_revision = '1544e1eed796'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column(u'users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_column(u'users', 'created_at')
    op.drop_column(u'users', 'updated_at')
    ### end Alembic commands ###
