"""empty message

Revision ID: bcce8739a0
Revises: None
Create Date: 2015-09-12 00:02:26.113977

"""

# revision identifiers, used by Alembic.
revision = 'bcce8739a0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.Unicode(length=100), nullable=False),
    sa.Column('name', sa.Unicode(length=200), nullable=True),
    sa.Column('password', sa.Unicode(length=100), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('clients',
    sa.Column('name', sa.Unicode(length=40), nullable=True),
    sa.Column('description', sa.Unicode(length=400), nullable=True),
    sa.Column('user_id', sa.Unicode(length=200), nullable=True),
    sa.Column('client_id', sa.Unicode(length=40), nullable=False),
    sa.Column('client_secret', sa.Unicode(length=55), nullable=False),
    sa.Column('is_confidential', sa.Boolean(), nullable=True),
    sa.Column('_redirect_uris', sa.UnicodeText(), nullable=True),
    sa.Column('_default_scopes', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_clients_client_secret'), 'clients', ['client_secret'], unique=True)
    op.create_table('grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Unicode(length=200), nullable=True),
    sa.Column('client_id', sa.Unicode(length=40), nullable=False),
    sa.Column('code', sa.Unicode(length=255), nullable=False),
    sa.Column('redirect_uri', sa.Unicode(length=255), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('_scopes', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grants_code'), 'grants', ['code'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Unicode(length=40), nullable=False),
    sa.Column('user_id', sa.Unicode(length=200), nullable=True),
    sa.Column('token_type', sa.Unicode(length=40), nullable=True),
    sa.Column('access_token', sa.Unicode(length=255), nullable=True),
    sa.Column('refresh_token', sa.Unicode(length=255), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('_scopes', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('refresh_token')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    op.drop_index(op.f('ix_grants_code'), table_name='grants')
    op.drop_table('grants')
    op.drop_index(op.f('ix_clients_client_secret'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('users')
    ### end Alembic commands ###
