"""empty message

Revision ID: dd76e297dee7
Revises: ccfc90dbff4f
Create Date: 2016-02-12 22:16:55.992738

"""

# revision identifiers, used by Alembic.
revision = 'dd76e297dee7'
down_revision = 'ccfc90dbff4f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_idx_user_id_follower_id', 'follows', ['user_id', 'follower_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_idx_user_id_follower_id', 'follows', type_='unique')
    ### end Alembic commands ###
