"""empty message

Revision ID: fe7ec9ca859d
Revises: dd76e297dee7
Create Date: 2016-05-03 15:04:08.632724

"""

# revision identifiers, used by Alembic.
revision = 'fe7ec9ca859d'
down_revision = 'dd76e297dee7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('followed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'followed_by_id', name='unique_idx_user_id_followed_by_id')
    )
    op.drop_table('follows')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], [u'users.id'], name=u'follows_follower_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'follows_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'follows_pkey')
    )
    op.drop_table('relationships')
    ### end Alembic commands ###
